# Generated by Django 4.2.2 on 2025-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('Unread', 'unread'), ('read', 'Read')], default='Unread', max_length=100),
        ),
    ]
